export type AdminSection =
  | "overview"
  | "sessions"
  | "customers"
  | "commission"
  | "employees"
  | "staff-management"
  | "branch-management"
  | "monthly"
  | "expenses"
  | "settings"
  | "retention"
  | "pricing"
  | "products"
  | "branch-pulse"

export { formatAmount as formatMoney } from "../../lib/format"
